resume-site-bucket-name   = "resume.yourenicked.net"
resume-index-file         = "resume"
fans-site-bucket-name     = "fans.yourenicked.net"
fans-fun-site-bucket-name = "onlyfans.yourenicked.net"
fans-index-file           = "fans"
tags_project              = "yourenicked"